name: MCCoroutine-Sample
version: 1.6.0
author: Shynixn
main: com.github.shynixn.mccoroutine.sample.MCCoroutineSamplePlugin
commands:
  mccor:
    description: Command for operations.
    useage: /<command>
    permission: mccoroutine.sample
    permission-message: You don't have permission.
